server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservicio
  application:
    name: CALIFICACION-SERVICE
  config:
    import: optional:configserver:http://localhost:8085